"use strict";
var RAW_DIRECTIVES=[
["BUTTON SELECTION ENDORSEMENT","Whenever someone presses a lift button—any button—say, “Excellent choice.”"],
["VERTICAL TRANSPORT PRESENTATION","When a lift arrives, gesture grandly towards it and say, “Your transport awaits.”"],
["JOURNEY COMMENCEMENT NOTICE","As the lift doors close, quietly say, “And so it begins.”"],
["FLOOR ARRIVAL MISIDENTIFICATION","Whenever a lift reaches a floor, say, “This is us,” even if you aren’t getting out."],
["PASSENGER DEPARTURE BRIEFING","As someone gets out of a lift, say, “Good luck out there.”"],
["SILENT JOURNEY CLOSURE","When leaving a completely silent lift, say, “Lovely talking to you all.”"],
["TRANSPORT ACCESS COMMENDATION","When someone holds the lift for you, say, “You’ve restored my faith in the system.”"],
["DELEGATION ABSENCE CONFIRMATION","If an empty lift arrives, inspect it and say, “Perfect—the delegation hasn’t arrived.”"],
["DEPARTURE QUALITY ASSESSMENT","As a lift begins moving, nod approvingly and say, “Textbook departure.”"],
["LATE PASSENGER ADMISSION","When lift doors reopen for a late arrival, announce, “We have a late entry!”"],
["VERTICAL AVIATION SIGN-OFF","At the end of a lift journey, say, “Thank you for flying with us.”"],
["DESTINATION ALIGNMENT DISCOVERY","When someone selects the same floor as you, say, “Ah—a fellow strategist.”"],
["AUTOMATED ACCESS AWARENESS","Whenever an automatic door opens, quietly say, “It knows.”"],
["DOORWAY ASSISTANCE RECOGNITION","When someone holds a door for you, say, “I won’t forget this.”"],
["ACCESS NEGOTIATION COMPLETION","When walking through an open door, say, “The access negotiations were successful.”"],
["SECURITY CLEARANCE VALIDATION","When someone uses their pass to let you through a secure door, say, “Your clearance checks out.”"],
["CORRIDOR SEPARATION PROTOCOL","When you and a colleague separate at a corridor junction, say, “We part ways here.”"],
["PEDESTRIAN CONVOY FORMATION","When someone is walking in the same direction as you, say, “Good—we’re forming a convoy.”"],
["FORWARD RECONNAISSANCE ASSIGNMENT","When overtaking someone in a corridor, say, “I’ll scout ahead.”"],
["STAKEHOLDER CONGESTION EVENT","When two people nearly collide in a doorway, say, “Classic stakeholder congestion.”"],
["MINOR REQUEST ESCALATION","Whenever someone asks you to do a trivial task, say, “I should be able to pull some strings.”"],
["MICRO-RELOCATION OWNERSHIP","When asked to move something a few inches, say, “Leave it with me.”"],
["REPROGRAPHIC CONTACT ACTIVATION","Before using the photocopier, say, “Don’t worry—I know a person.”"],
["ATTACHMENT DELIVERY MAGIC","Before attaching a document to an email, say, “Let me work my magic.”"],
["WINDOW CLOSURE FEASIBILITY","When asked to close a window, say, “I’ll see what I can do.”"],
["ILLUMINATION CONTACT STRATEGY","Before switching on a light, say, “I can make some calls.”"],
["WRITING INSTRUMENT FULFILMENT","When asked to pass someone a pen, say, “Consider it handled.”"],
["ELEVATED STORAGE TRANSFER","When asked to put something on a shelf, say, “I’ll take it upstairs.”"],
["FASTENING TECHNOLOGY DEPLOYMENT","Before using a stapler, say, “We have the technology.”"],
["PAPER FLOW INCIDENT EXPERTISE","Before clearing a paper jam, say, “I’ve dealt with this kind of situation before.”"],
["MESSAGE REDISTRIBUTION CHALLENGE","When asked to forward an email, sigh and say, “It won’t be easy.”"],
["FILENAME CHANGE ESTIMATE","Before changing a filename, say, “I’m going to need a few minutes.”"],
["CONTACT DATABASE ADVANTAGE","Before opening Outlook, say, “Fortunately, I have contacts.”"],
["COMMUNICATION EXPEDITION CONFIRMATION","Immediately after pressing Send, say, “I’ve expedited it.”"],
["REFRESHMENT INITIATIVE MOBILISATION","When walking towards the kettle, say, “The wheels are already in motion.”"],
["SEATING APPROVAL ACQUISITION","After borrowing a chair, say, “I’ve secured the necessary approvals.”"],
["PACKAGING BREAKTHROUGH REPORT","After successfully opening stubborn packaging, say, “We got it over the line.”"],
["PRINTER SUPPLY RECOVERY","After replacing the printer paper, say, “There were complications, but we prevailed.”"],
["ADHESIVE CONTINGENCY DEPLOYMENT","After fixing something with sticky tape, say, “I’ve deployed a workaround.”"],
["SPREADSHEET CONFIDENTIALITY DIRECTIVE","Before sharing a completely ordinary spreadsheet, say, “Let’s keep this between ourselves.”"],
["MEETING FORMATION CONFIRMATION","When everyone has arrived for a meeting, say, “The pieces are in position.”"],
["INFORMAL ENGAGEMENT OPENING","At the start of an informal conversation, say, “Thanks for making the time.”"],
["QUORUM STATUS ACHIEVED","When the final person joins a meeting, say, “Excellent—we’re quorate.”"],
["STRATEGIC SEATING ASSESSMENT","Before sitting down in a meeting room, ask, “Is this the strategic end of the table?”"],
["CLOSED-DOOR DISCLOSURE AUTHORISATION","When someone closes the meeting-room door, say, “Good. Now we can speak freely.”"],
["VISUAL FEED CONFIRMATION","When someone begins sharing their screen, say, “We have visual confirmation.”"],
["SLIDE ARRIVAL RECOGNITION","Whenever a presentation advances to a new slide, quietly say, “There it is.”"],
["OBVIOUS INSIGHT RECLASSIFICATION","When someone makes an extremely obvious point, nod gravely and say, “That changes everything.”"],
["SCREEN VISIBILITY AUDIO RESPONSE","When asked whether you can see someone’s screen, reply, “Loud and clear.”"],
["GEOMETRIC QUALITY ASSURANCE","Whenever someone draws a rough circle on a whiteboard, say, “That’s a very strong circle.”"],
["EARLY ADJOURNMENT SUCCESS","When a meeting finishes early, say, “An unprecedented operational success.”"],
["EXTENDED SESSION CASUALTY NOTICE","When a meeting runs late, say, “We always knew there would be casualties.”"],
["QUESTION ABSENCE INTERPRETATION","When nobody has any questions, say, “The silence speaks volumes.”"],
["OFFLINE ESCALATION DOCUMENTATION","When someone says, “Let’s take that offline,” look impressed and write it down."],
["REFRESHMENT PHASE ACTIVATION","When refreshments arrive during a meeting, say, “Excellent—the second phase.”"],
["ROUTINE AGENDA RISK WARNING","Introduce a completely ordinary agenda item by saying, “Now we reach the difficult part.”"],
["TEMPORARY ATTENDEE ABSENCE","When someone temporarily leaves a meeting, say, “We’ll continue in their absence.”"],
["INCONCLUSIVE ACTION ALIGNMENT","At the end of an inconclusive meeting, say, “I think we all know what we have to do.”"],
["NOTEBOOK CLOSURE RATIFICATION","When closing your notebook at the end of a meeting, say, “Then it’s settled.”"],
["MEETING SERVICE RECOGNITION","As people leave a meeting, say, “Thank you for your service.”"],
["MICROPHONE ACCESS CONFIRMATION","When someone unmutes during a video call, say, “We have you.”"],
["AUDIO RESTORATION NOTICE","When someone on a video call asks, “Can you hear me?” reply, “We can now.”"],
["CAMERA FEED RESTORATION","When someone’s camera switches on, say, “Visuals restored.”"],
["PARTICIPANT SIGNAL LOSS","When someone freezes during a video call, say, “We’ve lost them.”"],
["TEMPORAL RECONNECTION WELCOME","When a frozen colleague begins moving again, say, “Welcome back. It’s been years.”"],
["SIMULTANEOUS TRANSMISSION EVENT","When two people speak simultaneously on a video call, say, “Cross-channel interference.”"],
["UNSCHEDULED SCREEN DISCLOSURE","When someone accidentally shares the wrong window, say, “Interesting—very revealing.”"],
["TECHNOLOGY RESILIENCE CONFIRMATION","When screen sharing works on the first attempt, say, “The technology has held.”"],
["BACKGROUND PROTECTION ENQUIRY","When someone’s background blur behaves strangely, ask, “Are you entering the witness protection programme?”"],
["LATE REMOTE ARRIVAL RESPONSE","When someone joins a video call late, say, “We were beginning to fear the worst.”"],
["ANIMAL COUNSEL APPEARANCE","When a pet appears during a video call, say, “I see you’ve brought legal counsel.”"],
["JUNIOR STAKEHOLDER ARRIVAL","When a child appears during a video call, say, “Our newest stakeholder has joined us.”"],
["MUTED SPEECH REASSURANCE","When someone realises they have been speaking on mute, say, “We heard the entire speech in silence.”"],
["REMOTE DEPARTURE SALUTE","When everyone waves goodbye at the end of a video call, perform an unnecessarily solemn salute."],
["FINAL PARTICIPANT DISCLOSURE","When you are the last person left on a video call, wait two seconds and say, “Finally.”"],
["GRATITUDE LOOP CONTINUATION","Whenever an email exchange reaches “Thanks,” reply with “No problem” and keep the ceremony going for as long as possible."],
["OPERATIONAL SIGN-OFF STANDARD","End a routine email with, “Yours in operational readiness.”"],
["EXTENSIVE CONSULTATION PREAMBLE","Begin a one-line email with, “Following extensive internal consultation…”"],
["DOSSIER CLASSIFICATION PROCEDURE","Whenever attaching an ordinary file, refer to it as “the supporting dossier.”"],
["TYPOGRAPHICAL RECORD CORRECTION","After correcting a typo, announce, “The record has been amended.”"],
["SITUATIONAL AWARENESS FORWARDING","When forwarding an unimportant email, write, “For situational awareness.”"],
["CATERING PATHWAY DISTRIBUTION","When sending someone a menu, write, “Please find the available pathways attached.”"],
["COMMAND CHANNEL DESIGNATION","Whenever referring to the workplace group chat, call it “the command channel.”"],
["LUNCH IMAGE ESCALATION","When someone posts a photograph of their lunch, reply, “This has been escalated.”"],
["ANIMATED CONTEXT ACKNOWLEDGEMENT","When someone sends a GIF in a work chat, reply, “Useful context, thank you.”"],
["BINARY INDICATOR ASSESSMENT","When asked a simple yes-or-no question, reply, “All indicators point to yes.”"],
["COURSE MAINTENANCE RESPONSE","When someone gives you an ordinary update, reply, “Understood. Maintain course.”"],
["MILK ORDER CASE CLOSURE","After confirming the office milk order, say, “No further action is required at this time.”"],
["CALENDAR SUMMONS CLASSIFICATION","Whenever someone sends a calendar invitation, refer to it as “the formal summons.”"],
["IMMEDIATE DE-PRIORITISATION ORDER","Mark a thoroughly unimportant message, “For immediate de-prioritisation.”"],
["GOVERNANCE CLOSING STATEMENT","Finish a routine workplace announcement with, “Please govern yourselves accordingly.”"],
["PREMATURE OPERATIONAL INVOLVEMENT","When someone includes you in an email by mistake, reply, “I believe I have been brought into this operation prematurely.”"],
["THREAD INVOLVEMENT TERMINATION","When removed from an email thread, announce, “My involvement in the matter has concluded.”"],
["BISCUIT BREAKING NEWS ALERT","Write “BREAKING” in the group chat before announcing that biscuits have arrived."],
["COMMUNIQUÉ ISSUANCE CONFIRMATION","After posting an ordinary message in Teams or Slack, say, “I’ve issued a communiqué.”"],
["MORALE BEVERAGE INTERVENTION","When someone makes tea, say, “Good. Morale was becoming an issue.”"],
["COFFEE PRODUCTION RESUMPTION","When you discover fresh coffee, announce, “Production has resumed.”"],
["THERMAL OBJECTIVE ACHIEVED","When the kettle boils, say, “We have achieved temperature.”"],
["BISCUIT GOVERNANCE ENQUIRY","When someone offers you a biscuit, ask, “What’s the governance around these?”"],
["BISCUIT PORTFOLIO ASSESSMENT","When presented with a selection of biscuits, inspect them and say, “A strong portfolio.”"],
["DAIRY SUPPLY CHAIN EVENT","When the milk carton is empty, announce, “We have a supply-chain event.”"],
["DAIRY CONTINUITY RESTORATION","When fresh milk arrives, announce, “Business continuity has been restored.”"],
["REFRIGERATION SITE CLEARANCE","When looking into an empty office fridge, say, “They’ve cleared the site.”"],
["CAKE AUTHORISATION ENQUIRY","When someone brings in cake, ask, “Who authorised this—and how do we thank them?”"],
["CAKE STAKEHOLDER VERIFICATION","Before cutting a cake, ask, “Are all key stakeholders present?”"],
["VESSEL SELECTION APPRAISAL","When someone chooses a mug, say, “That’s one of our stronger vessels.”"],
["SCALABLE COFFEE DELIVERY","After making instant coffee, say, “It’s not glamorous, but it’s scalable.”"],
["TOAST DELIVERY SCHEDULE","When toast pops out of the toaster, say, “Right on schedule.”"],
["LIQUID CONTAINMENT FAILURE","When someone spills a tiny amount of water, announce, “Containment has failed.”"],
["SPILL INCIDENT CLOSURE","After wiping up a small spill, say, “The incident is now closed.”"],
["MIDDAY DELIVERABLE DESIGNATION","Whenever discussing lunch, refer to it as “the midday deliverable.”"],
["LUNCH MISSION DEBRIEF","When someone returns from lunch, ask, “Was the mission successful?”"],
["EXTERNAL CATERING CONSULTANTS","When a takeaway delivery arrives, announce, “The external consultants are here.”"],
["BANANA CALL ESCALATION","Hold a banana to your ear and say, “I’m afraid I have to take this.”"],
["MUNDANE BENEDICTION PROTOCOL","Occasionally end a mundane instruction with “Amen,” then continue as though nothing unusual happened."],
["HISTORIC PRINTER PERFORMANCE","When the printer works on the first attempt, say, “We are witnessing history.”"],
["PROPOSAL REJECTION BY PRINTER","When the printer fails, say, “It has rejected the proposal.”"],
["PRINT OFFERING SUBMISSION","Before pressing Print, say, “Let’s see if it accepts the offering.”"],
["DOCUMENT RELEASE ANNOUNCEMENT","When a printed page emerges, announce, “The documents have been released.”"],
["ENGINEERING ROLE ASSIGNMENT","When someone clears a printer jam, address them as “Engineering.”"],
["RECORDS MANAGEMENT DESIGNATION","Whenever referring to the shredder, call it “Records Management.”"],
["FASTENING SOLUTION APPROVAL","Before using a stapler, ask, “Is this the approved fastening solution?”"],
["PEN CUSTODY ADVISORY","When handing someone a pen, say, “Use it wisely.”"],
["WRITING ASSET RETIREMENT","When a pen runs out, hold it solemnly and say, “It gave everything.”"],
["PEN OPERABILITY CERTIFICATION","After testing a pen, nod seriously and say, “It’s operational.”"],
["SCISSOR SAFE-RETURN REQUEST","When someone borrows your scissors, say, “Bring them home safely.”"],
["INDUSTRIAL PAPERCLIP CLASSIFICATION","Whenever you see an unusually large paperclip, describe it as “industrial grade.”"],
["LAPTOP LIFE-SUPPORT INITIATION","When plugging in a laptop, say, “Commencing life support.”"],
["NETWORK GRID RECONNECTION","When the Wi-Fi reconnects, announce, “We’re back on the grid.”"],
["TECHNICAL RESCUE RECOGNITION","When an IT colleague fixes a minor problem, say, “You’ve saved more than you know.”"],
["ANCIENT RESTART PROTOCOL","When turning something off and on fixes it, say, “The ancient protocol remains effective.”"],
["VOICE-ACTIVATED EQUIPMENT PILOT","Put a removable “VOICE ACTIVATED” sign on a suitable, non-critical office appliance."],
["KEYBOARD LOADING ADVISORY","Put a removable note on a keyboard saying, “Please wait—keyboard loading.”"],
["CONNECTOR TYPE INTERROGATION","When someone asks to borrow a charger, lower your voice and ask, “What connector?”"],
["FINAL LINK INSTALLATION","Whenever plugging in an HDMI cable, refer to it as “the final link.”"],
["PERSONNEL ARRIVAL CONFIRMATION","When someone arrives at work, look relieved and say, “There they are.”"],
["PUNCTUALITY PERFORMANCE NOTICE","When someone arrives exactly on time, look at the clock and say, “Impeccable.”"],
["MINOR LATENESS OBSERVATION","When someone arrives one minute late, silently tap your watch."],
["TEMPORARY ABSENCE COVERAGE","When someone returns from the toilet, say, “Welcome back. We covered for you.”"],
["OUTERWEAR DEPARTURE ENQUIRY","Whenever someone puts on their coat, ask, “Going somewhere?”"],
["DAILY HISTORIC CLOSURE","At the end of the working day, say, “Another one for the history books.”"],
["EARLY EXTRACTION ADVISORY","When someone leaves work early, say, “Get out while you still can.”"],
["FINAL DEFENCE STAFFING","When only you and one colleague remain in the office, say, “We’re the last line of defence.”"],
["MONDAY RECALL CONFIRMATION","On Monday morning, say, “I see we’ve all been recalled.”"],
["FRIDAY EXTRACTION FORECAST","On Friday afternoon, announce, “Extraction is imminent.”"],
["POST-HOLIDAY DESK PRESERVATION","When someone returns from holiday, say, “Your desk has been preserved exactly as you left it.”"],
["LUNCH EXPEDITION HOMECOMING","Welcome a colleague back from lunch as though they have returned from a dangerous expedition."],
["INITIAL SNEEZE REGISTRATION","When someone sneezes once, say, “Noted.”"],
["REPEATED NOTIFICATION ACKNOWLEDGEMENT","When someone sitting near you sneezes more than once, say, “We heard you the first time.”"],
["UNIFORM GUIDANCE CONFIRMATION","When three colleagues wear the same colour, announce, “Good—the uniform guidance reached everyone.”"],
["SANDWICH PROCUREMENT DECISION","When someone chooses a sandwich, describe it as “a strategic procurement decision.”"],
["DESK TRANSFORMATION PROGRAMME","When people change desks, describe it as “an organisational transformation.”"],
["ENVIRONMENTAL WINDOW INTERVENTION","When someone opens a window, call it “an environmental intervention.”"],
["SEATING RESOURCE REALLOCATION","When someone changes seats, call it “a resource reallocation.”"],
["KITCHEN CROSS-FUNCTIONAL INITIATIVE","When tidying the office kitchen, announce, “This is a cross-functional initiative.”"],
["MANUAL TRANSPORT CONTINGENCY","When taking the stairs instead of the lift, say, “We’re using the manual contingency.”"],
["OFF-SITE PERIMETER ACTIVITY","When going for a walk around the block, announce, “I’m heading off-site.”"],
["INFORMAL MARKET INTELLIGENCE","Whenever someone shares office gossip, describe it as “informal market intelligence.”"],
["LEGACY FOOD ASSET STATUS","When discussing leftovers, refer to them as “legacy assets.”"],
["SHORT-TERM PEN PARTNERSHIP","When borrowing a pen, describe the arrangement as “a short-term equipment partnership.”"],
["ASSET TRACKING DISCREPANCY","When someone loses a borrowed pen, call it “an asset-tracking discrepancy.”"],
["RELAXED GOVERNANCE WINDOW","On casual Friday, announce, “The relaxed governance window is now open.”"],
["SEATING CONTINUITY RISK","When discovering a broken chair, announce, “We have a seating continuity risk.”"],
["THERMAL STRATEGY PIVOT","When turning up the heating, say, “We’re implementing a thermal strategy pivot.”"],
["PIZZA SERVICE OUTSOURCING","When ordering pizza, say, “We’ve decided to outsource.”"],
["CHIP PORTFOLIO ACQUISITION","When accepting someone’s unwanted chips, describe it as “an acquisition.”"],
["MUG ASSET MAINTENANCE","When washing a mug, say, “Just carrying out some routine asset maintenance.”"],
["GREEN INFRASTRUCTURE RELOCATION","When moving an office plant, call it “a green infrastructure project.”"],
["LUNCH LOCATION STRATEGY","When deciding where to have lunch, say, “We need to agree our location strategy.”"],
["ANNUAL STAKEHOLDER SUMMIT","Whenever discussing the office Christmas party, call it “the annual stakeholder summit.”"],
["BOTANICAL ROLE APPOINTMENT","Give the office plant a formal job title and occasionally ask for its opinion."],
["NORTHERN FACILITY DESIGNATION","Choose an underused meeting room and refer to it exclusively as “the northern facility.”"],
["TRIVIAL PERFORMANCE LEAGUE","Maintain a completely serious league table for trivial workplace achievements."],
["MINUTE-BASED EMPLOYEE AWARD","Award someone “Employee of the Minute” for a tiny act of competence."],
["CEREMONIAL ARTEFACT SELECTION","Select an ordinary office object as the department’s ceremonial artefact."],
["FRIDAY CASUAL PROTOCOL","Every Friday morning, announce, “Casual protocols are now in effect.”"],
["PRINTER INCIDENT NAMING SCHEME","Give every recurring printer fault an official incident name."],
["BISCUIT ABSENCE MONITORING","Maintain a “Days Since Last Biscuit” counter."],
["KETTLE PERFORMANCE REVIEW","Conduct a formal performance review of the temperamental office kettle."],
["TEN-SECOND PEN RETIREMENT","Hold a ten-second retirement ceremony whenever a pen runs out."],
["PREFERRED VESSEL SUPPLIER","Designate one mug brand as “the organisation’s preferred vessel supplier.”"],
["EXECUTIVE SEATING DESIGNATION","Choose one ordinary office chair and refer to it as “the executive suite.”"],
["TECHNICAL MERIT PROMOTION","Whenever someone fixes a minor technical problem, immediately promote them."],
["SECONDARY INFLUENCE INTRODUCTION","Introduce a colleague as “the person behind the person.”"],
["QUARTERLY TEA CONTRIBUTOR","Refer to whoever most recently made tea as “this quarter’s outstanding contributor.”"],
["CLIPBOARD LUNCH INTELLIGENCE","Carry a clipboard containing nothing except strongly held lunch opinions."],
["BISCUIT PACKET SIGN-OFF","Ask for verbal sign-off before opening a new packet of biscuits."],
["CENTRAL STORES RECLASSIFICATION","Refer to the stationery cupboard exclusively as “Central Stores.”"],
["PERSONAL EFFECTS RECLASSIFICATION","Refer to the coat rack exclusively as “Personal Effects.”"],
["PHOTOCOPIER COMPETITIVE FRAMEWORK","Establish a completely fictional rivalry between two photocopiers."],
["DIPLOMATIC POST HANDLING","Treat every arrival of post as though it were a diplomatic pouch."],
["ERRAND RETURN PRESS CONFERENCE","Hold a one-question press conference whenever someone returns from an errand."],
["DRAMATIC PROJECT NOMENCLATURE","Give every mundane office task an unnecessarily dramatic project name."],
["DOCTRINAL PROCESS CONCLUSION","After explaining a routine process, finish with, “And that is the doctrine.”"],
["CLASSIFIED TASK CODENAME","Give a trivial task a secret code name and politely refuse to explain it."],
["MICROWAVE LAUNCH CLEARANCE","Before starting the microwave, ask, “Are we cleared to proceed?”"],
["AUTOMATIC LIGHT GRATITUDE","Whenever automatic lights switch on, look upwards and say, “Thank you.”"],
["MICROWAVE PERFORMANCE PRAISE","When the microwave finishes, pat it gently and say, “Outstanding work.”"],
["PRINTER FOLLOW-UP APPOINTMENT","After successfully printing something, look at the printer and say, “Same time tomorrow.”"],
["END-OF-DAY CAPACITY LIMIT","At precisely 5 p.m., close your laptop and say, “They can’t ask any more of us.”"],
["VERBAL RECOVERY RECOGNITION","After a colleague stumbles over their words, say, “Couldn’t have said it better myself.”"],
["LITERARY PERFORMANCE REVIEW","After a colleague gets tongue-tied, say, “And they said Shakespeare is dead.”"],
["ELOQUENCE CAPABILITY ASSESSMENT","After a colleague struggles to get their words out, say, “You just have such a way with words.”"],
["ARTICULATION DIFFICULTY STATEMENT","After a colleague trips over a sentence, say, “That’s easy for you to say.”"],
["ATTENDANCE RECOVERY NOTICE","When someone arrives late at the office, say, “Cancel the search party.”"],
["REMOTE WORKSTATION TRANSFER","When helping at someone else’s desk and asking to take control of their computer, say, “Mind if I drive?”"],
["TEMPORARY COMMAND DELEGATION","When leaving your desk to go to the toilet, tell a colleague, “You’re in charge while I’m gone.”"],
["CONTINGENCY NARRATIVE PROTOCOL","When leaving your desk to go to the toilet, tell a colleague, “If I don’t make it back, tell my story.”"],
["UNSCRIPTED MEETING PARTICIPATION","When someone asks whether you have any questions in a meeting, say, “I don’t have any speaking lines in this scene.”"],
["EMOTIONAL STABILITY CONFIRMATION","Immediately after completely losing your cool over something, say, “Whoa, almost lost my cool there.”"],
["SPECIALIST RESOURCE ALLOCATION","When asked to complete a very straightforward task, say, “Boy, did you come to the right person.”"],
["DISCRETIONARY EXCEPTION AUTHORISATION","When asked to complete a very straightforward task, sigh and say, “Only because it’s you.”"],
["SEASONAL OPERATIONS SUSPENSION","After any minor inconvenience at work, say, “That’s it—Christmas is cancelled.” This is especially effective nowhere near Christmas."],
["REFRESHMENT RISK DECLARATION","Whenever a colleague offers you something such as tea or coffee, say, “Why the hell not? I’m not driving.”"],
["EXTERNAL OPPORTUNITY DETECTION","When a colleague arrives looking slightly smarter than usual, ask, “So, what time is your interview?”"],
["LIMITED LIABILITY ACKNOWLEDGEMENT","Whenever something was entirely your fault, say, “I can’t help but feel partially responsible.”"],
["JUDICIAL QUESTION CLOSURE","Immediately after asking a question in a meeting, say, “No further questions, Your Honour.”"],
["SELF-DIRECTED IDEATION CALIBRATION","After offering the first idea in a brainstorming session, say, “That’s great—let’s get the bad ideas out of the way first.”"],
["WORKSTATION ACCESS PETITION","Whenever you need to speak to someone at their desk, ask, “Permission to approach the bench?”"],
["AUTOGRAPH FULFILMENT SERVICE","Whenever you are asked to sign something at work, say, “Anything for a fan.”"],
["EARLY DEPARTURE CLASSIFICATION","If anyone leaves the office even a minute before 5 p.m., ask, “Half day, is it?”"],
["CONSENSUS IMPOSSIBILITY NOTICE","When a colleague says something you disagree with, say, “I’d love to agree with you, but then we’d both be wrong.”"],
["DELAYED ATTENDANCE DISCLOSURE","When you arrive late at the office or a meeting, say, “Sorry I’m late—I didn’t want to come.”"],
["MATERIAL TRANSFER REFUSAL","When a colleague tries to hand you something, say, “No thanks, I’m trying to quit.”"],
["UNPLANNED FLOOR PLACEMENT","When someone accidentally drops something, say, “Oh, yeah—just put that anywhere.”"],
["EXPEDITED ASSET RECOVERY","When someone accidentally drops something, immediately pick it up and say, “Finders keepers.”"],
["OBJECT HANDLING COMPLIANCE","When someone accidentally drops something, say, “Oh, we actually don’t do that here.”"],
["RECURRING FLOOR-LEVEL ENGAGEMENT","When helping someone pick up something they dropped, say, “We’ve got to stop meeting like this.”"],
["COURTESY RESPONSE DEFERRAL","When someone tells you to have a nice day, reply, “I’ll think about it.”"],
["UNSOLICITED INSTRUCTION REJECTION","When someone tells you to have a nice day, reply, “Don’t tell me what to do.”"],
["ON-SITE INTERRUPTION APOLOGY","Whenever you need to speak to a co-worker, begin with, “Sorry to bother you at work…”"],
["OBJECTIVE UNCERTAINTY RESPONSE","When someone asks a question with an objectively correct answer, such as when today’s meeting starts, say, “There’s no way to know.”"]
];
var DIRECTIVES=RAW_DIRECTIVES.map(function(item,index){return{id:"directive-"+String(index+1).padStart(3,"0"),number:index+1,heading:item[0],text:item[1]};});
